/**
 * Build Intra's extracted brand derivatives from the canonical code sources.
 *
 * This script does not design a new mark. MARK_BODY is the exact geometry in
 * src/components/brand/Mark.tsx. FAVICON_BODY is the existing small-size
 * adaptation in src/app/icon.svg. App icons are copied byte-for-byte from the
 * committed PWA outputs generated by scripts/generate-icons.mjs.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import sharp from "sharp";

const ROOT = process.cwd();
const BRAND = join(ROOT, "brand");
const INK = "#1f1e1d";
const TEXT = "#141413";
const MUTED = "#3d3d3a";
const IVORY = "#faf9f5";
const SAGE = "#dfe9df";
const MIST = "#ccdbe8";
const BORDER = "#dedcd1";

const MARK_BODY = (color) => `
  <circle cx="9.5" cy="16" r="4.5" fill="${color}"/>
  <circle cx="22.5" cy="16" r="4.5" fill="none" stroke="${color}" stroke-width="2.2"/>
  <line x1="14" y1="16" x2="18" y2="16" stroke="${color}" stroke-width="2.2"/>`;

const FAVICON_BODY = `
  <circle cx="9.5" cy="16" r="4.8" fill="${INK}"/>
  <circle cx="22.5" cy="16" r="4.8" fill="none" stroke="${INK}" stroke-width="2.6"/>
  <line x1="14" y1="16" x2="18" y2="16" stroke="${INK}" stroke-width="2.6"/>`;

function svg(width, height, body, attrs = "") {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" ${attrs}>${body}\n</svg>\n`;
}

function markSvg(color = INK, size = 32) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 32 32">${MARK_BODY(color)}\n</svg>\n`;
}

async function output(path, data) {
  const absolute = join(BRAND, path);
  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, data);
}

async function raster(svgSource, path, width, height = width) {
  const png = await sharp(Buffer.from(svgSource)).resize(width, height).png().toBuffer();
  await output(path, png);
}

function placedMark({ x, y, size, color }) {
  const scale = size / 32;
  return `<g transform="translate(${x} ${y}) scale(${scale})">${MARK_BODY(color)}</g>`;
}

function profileSvg(size) {
  const markSize = size * 0.56;
  return svg(
    size,
    size,
    `<rect width="${size}" height="${size}" fill="${INK}"/>\n${placedMark({ x: (size - markSize) / 2, y: (size - markSize) / 2, size: markSize, color: IVORY })}`,
  );
}

function coverSvg(width, height) {
  const markSize = Math.min(height * 0.42, 128);
  return svg(
    width,
    height,
    `<rect width="${width}" height="${height}" fill="${IVORY}"/>\n` +
      `<rect x="1" y="1" width="${width - 2}" height="${height - 2}" fill="none" stroke="${BORDER}" stroke-width="2"/>\n` +
      `${placedMark({ x: (width - markSize) / 2, y: (height - markSize) / 2, size: markSize, color: INK })}`,
  );
}

function templateSvg(width, height, kind) {
  const margin = Math.round(Math.min(width, height) * 0.075);
  const markSize = Math.round(Math.min(width, height) * 0.09);
  const headlineSize = Math.round(Math.min(width, height) * 0.065);
  const bodySize = Math.round(headlineSize * 0.34);
  const footerY = height - margin;
  const backgroundAccent = kind === "portrait" || kind === "story" ? SAGE : MIST;
  const body = `<rect width="${width}" height="${height}" fill="${IVORY}"/>
  <rect x="${margin}" y="${margin}" width="${width - margin * 2}" height="${height - margin * 2}" rx="${Math.round(markSize * 0.18)}" fill="none" stroke="${BORDER}" stroke-width="2"/>
  <circle cx="${width - margin * 1.45}" cy="${margin * 1.35}" r="${Math.round(markSize * 0.72)}" fill="${backgroundAccent}" opacity="0.7"/>
  ${placedMark({ x: margin, y: margin, size: markSize, color: INK })}
  <g id="editable-content" font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif" fill="${TEXT}">
    <text x="${margin}" y="${Math.round(height * 0.42)}" font-size="${bodySize}" font-weight="600" letter-spacing="${Math.max(2, Math.round(bodySize * 0.08))}">[EYEBROW]</text>
    <text x="${margin}" y="${Math.round(height * 0.52)}" font-family="Iowan Old Style, Palatino Linotype, Palatino, Georgia, serif" font-size="${headlineSize}" font-weight="400" letter-spacing="-${Math.max(1, Math.round(headlineSize * 0.02))}">[HEADLINE]</text>
    <text x="${margin}" y="${Math.round(height * 0.59)}" font-size="${bodySize}" fill="${MUTED}">[SUPPORTING DETAIL]</text>
  </g>
  <line x1="${margin}" y1="${footerY - bodySize * 1.7}" x2="${width - margin}" y2="${footerY - bodySize * 1.7}" stroke="${BORDER}" stroke-width="2"/>
  <text x="${margin}" y="${footerY - Math.round(bodySize * 0.3)}" font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif" font-size="${bodySize}" fill="${MUTED}">Intra</text>`;
  return svg(width, height, body, `data-template="${kind}"`);
}

function ogSvg() {
  return svg(
    1200,
    630,
    `<rect width="1200" height="630" fill="${IVORY}"/>
  ${placedMark({ x: 80, y: 64, size: 48, color: INK })}
  <text x="146" y="100" font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif" font-size="34" font-weight="700" fill="${TEXT}">Intra</text>
  <text x="80" y="315" font-family="Iowan Old Style, Palatino Linotype, Palatino, Georgia, serif" font-size="62" font-weight="400" letter-spacing="-1.2" fill="${TEXT}">Tell Intra what you need.</text>
  <text x="80" y="385" font-family="Iowan Old Style, Palatino Linotype, Palatino, Georgia, serif" font-size="62" font-weight="400" letter-spacing="-1.2" fill="${TEXT}">Get a real price. Keep the final say.</text>
  <text x="80" y="460" font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif" font-size="27" fill="${MUTED}">A structured brief in, a genuine printer quote out,</text>
  <text x="80" y="498" font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif" font-size="27" fill="${MUTED}">a human-approved WhatsApp handoff.</text>
  <g font-family="ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif" font-size="20" fill="${INK}">
    <rect x="80" y="545" width="190" height="46" rx="23" fill="${SAGE}"/><text x="101" y="575">No fund custody</text>
    <rect x="284" y="545" width="247" height="46" rx="23" fill="${SAGE}"/><text x="305" y="575">Human-approved orders</text>
    <rect x="545" y="545" width="208" height="46" rx="23" fill="${SAGE}"/><text x="566" y="575">Nothing fabricated</text>
  </g>`,
  );
}

await output("logo/intra-mark.svg", markSvg(INK));
await output("logo/intra-mark-monochrome.svg", markSvg("#000000"));
await output("logo/intra-mark-reversed.svg", markSvg(IVORY));
await output(
  "logo/intra-mark-on-ivory.svg",
  svg(
    512,
    512,
    `<rect width="512" height="512" fill="${IVORY}"/>\n${placedMark({ x: 128, y: 128, size: 256, color: INK })}`,
  ),
);
await output(
  "logo/intra-mark-on-ink.svg",
  svg(
    512,
    512,
    `<rect width="512" height="512" rx="96" fill="${INK}"/>\n${placedMark({ x: 128, y: 128, size: 256, color: IVORY })}`,
  ),
);

for (const size of [512, 1024, 2048]) {
  await raster(markSvg(INK, size), `logo/png/intra-mark-${size}.png`, size);
}

const faviconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">${FAVICON_BODY}\n</svg>\n`;
await output("logo/favicon/intra-favicon.svg", faviconSvg);
for (const size of [16, 32, 48]) {
  await raster(faviconSvg, `logo/favicon/intra-favicon-${size}.png`, size);
}

const appCopies = [
  ["public/icons/apple-touch-icon.png", "logo/app-icons/intra-apple-touch-180.png"],
  ["public/icons/icon-192.png", "logo/app-icons/intra-app-icon-192.png"],
  ["public/icons/icon-512.png", "logo/app-icons/intra-app-icon-512.png"],
  ["public/icons/icon-maskable-512.png", "logo/app-icons/intra-app-icon-maskable-512.png"],
];
for (const [source, destination] of appCopies)
  await output(destination, await readFile(join(ROOT, source)));

const socials = [
  ["social/x/intra-x-profile-400.png", profileSvg(400), 400, 400],
  ["social/x/intra-x-header-1500x500.png", coverSvg(1500, 500), 1500, 500],
  ["social/instagram/intra-instagram-profile-320.png", profileSvg(320), 320, 320],
  ["social/linkedin/intra-linkedin-profile-400.png", profileSvg(400), 400, 400],
  ["social/linkedin/intra-linkedin-company-cover-1512x256.png", coverSvg(1512, 256), 1512, 256],
  ["social/whatsapp/intra-whatsapp-profile-640.png", profileSvg(640), 640, 640],
];
for (const [path, source, width, height] of socials) {
  await output(path.replace(/\.png$/, ".svg"), source);
  await raster(source, path, width, height);
}

const templates = [
  ["templates/intra-social-square-1080x1080.svg", 1080, 1080, "square"],
  ["templates/intra-social-landscape-1600x900.svg", 1600, 900, "landscape"],
  ["templates/intra-social-portrait-1080x1350.svg", 1080, 1350, "portrait"],
  ["templates/intra-social-story-1080x1920.svg", 1080, 1920, "story"],
];
for (const [path, width, height, kind] of templates) {
  const source = templateSvg(width, height, kind);
  await output(path, source);
  await raster(source, path.replace(/\.svg$/, "-preview.png"), width, height);
}

const platformTemplates = [
  [
    "social/x/intra-x-square-post-1080x1080",
    "templates/intra-social-square-1080x1080.svg",
    1080,
    1080,
  ],
  [
    "social/x/intra-x-landscape-post-1600x900",
    "templates/intra-social-landscape-1600x900.svg",
    1600,
    900,
  ],
  [
    "social/x/intra-x-portrait-post-1080x1350",
    "templates/intra-social-portrait-1080x1350.svg",
    1080,
    1350,
  ],
  [
    "social/instagram/intra-instagram-square-1080x1080",
    "templates/intra-social-square-1080x1080.svg",
    1080,
    1080,
  ],
  [
    "social/instagram/intra-instagram-portrait-1080x1350",
    "templates/intra-social-portrait-1080x1350.svg",
    1080,
    1350,
  ],
  [
    "social/instagram/intra-instagram-story-1080x1920",
    "templates/intra-social-story-1080x1920.svg",
    1080,
    1920,
  ],
  [
    "social/linkedin/intra-linkedin-square-post-1080x1080",
    "templates/intra-social-square-1080x1080.svg",
    1080,
    1080,
  ],
  ["social/linkedin/intra-linkedin-landscape-post-1200x627", null, 1200, 627],
  [
    "social/whatsapp/intra-whatsapp-status-1080x1920",
    "templates/intra-social-story-1080x1920.svg",
    1080,
    1920,
  ],
];
for (const [base, sourcePath, width, height] of platformTemplates) {
  const source = sourcePath
    ? await readFile(join(BRAND, sourcePath), "utf8")
    : templateSvg(width, height, "landscape");
  await output(`${base}.svg`, source);
  await raster(source, `${base}.png`, width, height);
}

const og = ogSvg();
await output("social/intra-og-1200x630.svg", og);
await raster(og, "social/intra-og-1200x630.png", 1200, 630);

console.log("Built extracted Intra brand assets in brand/.");

// Build the extended social, presentation, screenshot, and diagram system.
await import("./build-social-system.mjs");
